#!/bin/sh
set -e

# Write .env from container environment when SECRETS_PATH is not used.
# Docker Compose injects vars from env_file before this script runs.
cat > .env << EOL
# Server Configuration
PORT=${PORT:-3000}
NODE_ENV=${NODE_ENV:-production}
LOG_LEVEL=${LOG_LEVEL:-info}

# Admin Credentials
ADMIN_USERNAME=${ADMIN_USERNAME:-}
ADMIN_PASSWORD=${ADMIN_PASSWORD:-}
ADMIN_EMAIL=${ADMIN_EMAIL:-}
ADMIN_FIRST_NAME=${ADMIN_FIRST_NAME:-}
ADMIN_LAST_NAME=${ADMIN_LAST_NAME:-}

# Company Details
COMPANY_NAME=${COMPANY_NAME:-}
COMPANY_ADDRESS=${COMPANY_ADDRESS:-}
COMPANY_PHONE=${COMPANY_PHONE:-}
COMPANY_EMAIL=${COMPANY_EMAIL:-}

# Security
BCRYPT_SALT_ROUNDS=${BCRYPT_SALT_ROUNDS:-12}
SESSION_SECRET=${SESSION_SECRET:-default-secret-change-in-production}
MAX_LOGIN_ATTEMPTS=${MAX_LOGIN_ATTEMPTS:-4}
LOCK_TIME=${LOCK_TIME:-15}

# Instance Information
INSTANCE_ID=${INSTANCE_ID:-}
DOMAIN=${DOMAIN:-}

# Optional test user seed (local Docker)
SEED_TEST_USERS=${SEED_TEST_USERS:-}
SECRETARY_USERNAME=${SECRETARY_USERNAME:-}
SECRETARY_PASSWORD=${SECRETARY_PASSWORD:-}
SECRETARY_EMAIL=${SECRETARY_EMAIL:-}
SECRETARY_FIRST_NAME=${SECRETARY_FIRST_NAME:-}
SECRETARY_LAST_NAME=${SECRETARY_LAST_NAME:-}
MECHANIC_USERNAME=${MECHANIC_USERNAME:-}
MECHANIC_PASSWORD=${MECHANIC_PASSWORD:-}
MECHANIC_EMAIL=${MECHANIC_EMAIL:-}
MECHANIC_FIRST_NAME=${MECHANIC_FIRST_NAME:-}
MECHANIC_LAST_NAME=${MECHANIC_LAST_NAME:-}
EOL

exec "$@"
